project:
  type: website
  output-dir: docs
  
website:
  title: "Shuai Wang"
  #favicon: "images/headshot.jpg"
  search: 
    location: navbar
    type: textbox
  navbar:
    left: 
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      
    right:
      #- icon: github
        #href: https://github.com/shuaiwo
      - icon: linkedin
        href: https://www.linkedin.com/in/shuaiws
        
format:
  html:
    theme: cosmo
    css: styles.css
    #code-link: true
    code-fold: true
    #code-tools: true
    highlight-style: github
    
editor: visual

